# Set update schedule for GitHub Actions
---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "mkriegs"
    commit-message:
      prefix: "Action Update"
    reviewers:
      - "mkriegs"