name: Linkedin blog post workflow
on:
#  schedule: # Run workflow automatically
#    - cron: "0 * * * *" # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly

jobs:
  linkedin_rss_job:
    runs-on: ubuntu-latest
    name: Post Latest RSS Post to Linkedin
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get Latest Post / Post On Linkedin
        uses: Arisamiga/Linkedin-RSS@dev-2
        with:
          feed_list: https://mkriegs.info/feed.xml # Url of RSS
          ln_access_token: ${{ secrets.ln_access_token }} # Url of LinkedIn Access Token
#          embed_image: https://mkriegs.info/assets/img/IMAGESTART.jpg # Url of embed image