name: Send Bluesky Post

on:
#  schedule: # Run workflow automatically
#    - cron: "* 16 * * 0,5,6" # Runs At every minute past hour 16 on Sunday, Friday, and Saturday.
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Send post to Bluesky
      id: bluesky_post_multiline
      uses: cbrgm/bluesky-github-action@v1
      with:
        handle: ${{ secrets.BLUESKY_HANDLE }}
        password: ${{ secrets.BLUESKY_PASSWORD }}
        text: |
          This is a multiline post sent from GitHub Actions.
          This example demonstrates how to include multiple lines in the `text` input.
